# Ejercicio día 8
**Programación I**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [1]:
import numpy as np

In [2]:
#x=10
#y=10
#mat1=np.zeros([x,y])
#y=np.arange(100)

#z=np.random.choice(y,int(x*(y/2),replace==false))

z=np.random.choice(2,int(10*(10/2),replace=false)
x[z]=1                   
x.resize(10,10)

SyntaxError: invalid syntax (<ipython-input-2-e8f58d26ca08>, line 9)

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



In [ ]:
mat1=np.zeros([5,2]) #Genera matriz de 0s de tamaño 5x2
mat2=np.ones([5,2]) #Genera matriz de 1s de tamaño 5x2

In [ ]:
col1=mat1.flatten("F") #Flatten, sirve para hacer un vector fila o columa, "F" sirve para agarrar todos los valores
col2=mat2.flatten("F")
a1=col1.reshape(10,1) #Hace que ahora la matriz sea vector columna

In [ ]:
a2=col2.reshape(10,1) #Hace qie ahora la matriz sea vector columna

In [ ]:
v1=a1[:np.newaxis] #método que agrega otra dimensión, de este lado salen las columnas.
v2=a2[:np.newaxis] 

In [ ]:
np.dstack((v1,v2)) #apila los vectores en una tercera dimensión

In [ ]:
a3=col1.reshape(1,10)
a4=col1.reshape(1,10) #ahora los hice fila

In [ ]:
np.vstack((a3,a4)) #las apila de forma vertical

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una matriz. 

In [ ]:
x=np.random.random([10,1])*100 #creamos vectores columna
y=np.random.random([10,1])*100
z=np.random.random([10,1])*100

mat=np.hstack((x,y,z)) #las apilo como columnas
mat

def f(x,y,z): #genero función
    return 2*x+3*y+z**2

f(x,y,z) #aplico la función a los vectores columna

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [ ]:
c1=np.random.choice(2,(50,50)) #Genero matriz de 0 y 1 con que represento cuadrado grandec1
c1

In [ ]:
c2=c1[14:34,14:34] #Recorto el cuadrado para tener el pequeño, pues comparten centro así queda el slicing
c2

In [ ]:
mat_n=c1>0 #hago una matriz, en donde veo cuales son mayores que 0 para el cuadro grande
mat_n

In [ ]:
z=mat_n #crea una matriz, que tenga solo unos de la matriz grande
z


In [ ]:
sum(sum(z)) #sumo los 1 del cuadro grande

In [ ]:
x=c2 #Matriz del cuadro pequeño que tiene unos 
sum(sum (x)) #sumo los 1 del cuadro pequeño

In [ ]:
area=2500*(sum(sum(x))/sum(sum(z))) #Obtengo la aproximación del área
area

## Tareas

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

## Array Creation Routines

In [ ]:
#Numpy.Empty
np.empty((2,3),dtype=float) #1.arg, es si será mat o tupla, #2type, si es entero o float, order 

In [ ]:
#numpy.array
np.array([1,2,3],) #1.arg, devuelve la lista como array

In [ ]:
#np.arange
np.arange(4,7,0.2) #Numero de inicio, #numero final, #como va avanzando

In [ ]:
#np.identity  #Devuelve una matriz identidad con el número que se le dió
np.identity(3)

In [ ]:
#np.ones #Devuelve una matriz de unos o un vector
np.ones(5)

In [ ]:
#np.full 
np.full((5,5),3) #La tupla es el tamaño, el otro valor como lo va a rellenar

In [ ]:
#np.copy
x=np.array([1,2,3])
z=np.copy(x) #Creo una copia de x para poder modificarla sin modificar la otra lista
z[0]=2
print(x)
print(z)

In [ ]:
#np.linspace
np.linspace(3,7,4) #Primer valor, inicio, segundo valor final, ultimo valor, en cuantas partes lo voy a dividir.

In [ ]:
#np.logspace
np.logspace(2,3,4) #devuelve numeros separados de forma igual en escala logarítmica.

In [ ]:
#np.vander
z=np.vander(x,5) #necesito un vector, este vector genera una matriz en donde las columnas son potencias del vector
               #en la primera es a la N, la segunda a la N-i hasta llegar a 0
z    
    

In [ ]:
#np.vander
np.diag(z,k=1) #necesita una matriz, devuelve la diagonal, el k, se va moviendo por las columnas iniciales

In [ ]:
#np.tri
np.tri(3,4,1) #Devuelve una matriz triangulada, primer numero filas, segundo numero columnas, tercer numero, en donde
            #comienza el 0, si no se pone inicia por default en la ultima fila

In [ ]:
#np.mat
h=np.array([[1,3,5,5],[1,3,5,4]])
l=np.asmatrix(h)
l
#convierte un array a un dato como matriz

In [ ]:
#np.full_like
np.full_like(x,3)  #Devuelve una matriz, con las mismas características que el vector llamado, lo devuelve con el numero 
                    #Que se indica

In [ ]:
#np.eye    #Tiene la misma funcionalidad de identity
np.eye(10)

In [ ]:
#np.triu   #Crean una matriz triangular inferior,k nos dice la columna en la que iniciran los 0 por debajo de ella 
np.triu(x,k=2)

In [ ]:
j=np.diagflat(z) #hace que todos los elementos de una matriz estén en una 
j

In [ ]:
np.ascontiguousarray(j) #crea un array que es contiguo

## Array manipulation routines

In [ ]:
np.shape(x) #devuelve la forma de un array, en este caso, nos está diciendo que no es realmente un array

In [ ]:
np.reshape(x,(3,1)) #da forma de matriz, en este caso de vector

In [ ]:
(np.ravel(x)) #devuelve una lista de los valores de una matriz

In [ ]:
#np.moveaxis
x=np.moveaxis(j,1,-2)
x
#mueve la matriz, en sus dimensiones, primer argumento matriz, , segundo columna que quiero cambiar, tercero es la columna a mover

In [ ]:
#np.swapaxes
o=np.arange(6).reshape(3,2)
np.swapaxes(o,1,0)
#practicamente transpone la matriz

In [3]:
#np.column stack
a=np.array((1,2,3))
n=np.array((4,5,6))
np.column_stack((a,n))
#Apila dos vectores, de forma que queden como vectores columna pegados

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
#np.concatenate
np.concatenate((a,n))
#concatena dos vectores, para que estos esten en un solo vector, realmente devuelve una lista, para cambiarlo, se hace reshape

array([1, 2, 3, 4, 5, 6])

In [5]:
#np.asscalar(a)
np.asscalar(np.array([24]))
#Devuelve el valor escalar de un vector de 1x1

24

In [6]:
#np.broadcast
x=np.array([[1],[2],[3]])
y=np.array([4,5,6])
b=np.broadcast(x,y)
i=np.empty(b.shape)
i.flat=[u+v for (u,v) in b]
i
#Sumas dos vectores, de tal forma que puede crear matrices, que son apiladas en forma de suma, para cada elemento de la mat

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [7]:
#np.delete
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr
np.delete(arr,1,1) 
#Elimina filas o columnas de una matriz, que están especificadas en los paréntesis

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [8]:
#np.vsplit
x=np.arange(16).reshape(2,8)
x
np.vsplit(x,2)
#Separa las matrices con vectores

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]

In [9]:
#np.resize
a=np.array([[0,1],[2,3]])
np.resize(a,(2,12))
#da un nuevo array con una forma específica

array([[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]])

In [10]:
#np.append
np.append([1,2,3],[[4,5,6],[8,9,10]])
#agrega los vectores como si fuera vectores filas

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [11]:
#np.hsplit
x=np.arange(16).reshape(4,4)
np.hsplit(x,2)
#Parte el vector de forma que quedan dos del mismo tamaño

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [12]:
#np.flip
A=np.arange(8).reshape(2,2,2)
A
np.flip(A,(0,2))
#Le da la vuelta a los elementos del vector através de la dimensión

array([[[5, 4],
        [7, 6]],

       [[1, 0],
        [3, 2]]])

In [13]:
#np.fliplr
A=np.diag([1.,2.,3.])
A
np.fliplr(A)
#voltea la diagonal de una matriz

array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

In [14]:
#np.stack
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.dstack((a,b))
#Apila vectores através de una tercera dimensión

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [15]:
#np.squeeze()
x = np.array([[[0], [1], [2]]])
x.shape

np.squeeze(x).shape

np.squeeze(x, axis=0).shape

#Quita matrices de una dimension de en la forma de un vector

(3, 1)

## Operaciones string

In [16]:
x1=np.array(["Hola"])
x2=np.array(["adios"])
np.char.add(x1,x2) #fusiona 2 vectores

array(['Holaadios'], dtype='<U9')

In [17]:
a=np.array(["Yo juego"])
i=np.array([1,2,3])
np.char.multiply(a,i) #Multiplica el vector, por lo que hay dentro de el 
                      #otro vector

array(['Yo juego', 'Yo juegoYo juego', 'Yo juegoYo juegoYo juego'],
      dtype='<U24')

In [18]:
np.char.mod(a,i)
#Genera un vector que se itera

array(['Yo juego', 'Yo juego', 'Yo juego'], dtype='<U8')

In [19]:
a=np.array(["ao juego"])
np.char.capitalize(a) #devuelve la primera letra del vector como mayus

array(['Ao juego'], dtype='<U8')

In [20]:
np.char.center(a,1) #Devuelve un vector que tiene solo la primera letra  o lo que se le especifique.

array(['a'], dtype='<U1')

In [21]:
a=np.array(["ao juego"])
np.char.expandtabs(a, tabsize=0) #da como resultado un vector en el que todas las letras estan separadas con el numero especificado

array(['ao juego'], dtype='<U8')

In [22]:
x2=np.array(["adios"])
a=np.array(["ao juego"])
np.char.join(x2,a)
#Da como resultado un string que es la concatenacion de los string de los vectores

array(['aadiosoadios adiosjadiosuadioseadiosgadioso'], dtype='<U43')

In [23]:
a=np.array(["ao juego"])
np.char.ljust(a,15)
#da como resultado al final de los espacios.

array(['ao juego       '], dtype='<U15')

In [24]:
a=np.array(["ESTO ES EL PES"])
np.char.lower(a)
#Devuelve el string como minúsculas

array(['esto es el pes'], dtype='<U14')

In [25]:
np.char.partition(a,x2) #para cada elemento del vector a, parte el elemento como la primera ocurrencia y devuelve 3 string que contienen la parte antes del separador|b

array([['ESTO ES EL PES', '', '']], dtype='<U14')

In [26]:
np.char.replace(a,x1,x2) #Para cada elemento de a, devuelve una copia de las recurrencias en el segundo parámetro, puestas en el tercero.

array(['ESTO ES EL PES'], dtype='<U14')

In [27]:
np.char.rjust(a,1) #Devuelve la posicion desde 1 de las letras del vector.

array(['E'], dtype='<U1')

In [28]:
np.char.rpartition(a,x2) #Devuelve para cada elemento de a las ultimas ocurrencias separadas y contenidas por la parte antes del separador.

array([['', '', 'ESTO ES EL PES']], dtype='<U14')

In [29]:
np.char.rsplit(a,a)
#regresa a 

array([list(['', ''])], dtype=object)

In [30]:
np.char.split(x1,a)
#Para cada elemento en a devuelve una lista de palabras usando el segundo argumento como el string delimitate

array([list(['Hola'])], dtype=object)

In [31]:
np.char.splitlines(a)
#Da una lista de las lineas que hay en el vector, en este caso solo 1

array([list(['ESTO ES EL PES'])], dtype=object)

In [32]:
np.char.translate(a,"AAAAAAAADSSAFSJSUSJSKSJUFNJSKAFNJSKANFSAÑNFASLÑFNSAKFNSAFÑKNASFLÑAF")
#Cambia los espacios por lugares en la table

array(['ESTOJESJELJPES'], dtype='<U14')

In [33]:
np.char.zfill(a,80)
#llena el vector con los espacios del vector que se invoca

array(['000000000000000000000000000000000000000000000000000000000000000000ESTO ES EL PES'],
      dtype='<U80')

In [34]:
np.char.equal(a,x1)
#Devuelve si los vectores son iguales.

array([False])

In [35]:
np.char.not_equal(a,x1)
#Devuelve si no son iguales lo vectores

array([ True])

In [36]:
np.char.greater_equal(a,x1)
#revisa si los arrays tienen la misma longitud

array([False])

In [37]:
np.char.less_equal(a,a)
#Devuelve si son iguales o menores, dice true, porque son lo mismo.

array([ True])

In [38]:
np.char.greater(a,x1)
#Me dice si una es mayor que la otra.

array([False])

In [39]:
np.char.less(x2,x1)
#compara si el primer argumento es menor que el segundo.

array([False])

In [40]:
np.char.endswith(a,"a")
#Devuelve si el vector termina con esa letra.

array([False])

In [41]:
np.char.find(a,"B") #Devuelve cual es el índice más bajo del vector.

array([-1])

In [42]:
np.char.isalpha(x1)
#Devuelve verdadero si todas las letras del vector son del alfabeto.

array([ True])

In [43]:
np.char.isalnum(a) #Devuelve verdadero si tiene caracteres alfanuméricos

array([False])

In [44]:
np.char.isdecimal(a)
#Devuelve verdadero, si solo tengo valores decimales en todos los caracteres del elemento.

array([False])

In [45]:
np.char.isdigit(x1)
#Devuelve verdadero si todos los elementos en el caracter son dígitos.

array([False])

In [46]:
np.char.islower(a)
#Devuelve verdadero si todos los elementos del vector están en minúsculas.

array([False])

In [47]:
np.char.isnumeric(a)
#Devuelve si es verdadero si todos los verdaderos son numéricos.

array([False])

In [48]:
a=np.array(["  "])
np.char.isspace(a)
#Devuelve verdadero si todos los caracteres son espaciones

array([ True])

In [49]:
np.char.rfind(a,"mnaskñfnsalñ",2)
#Para todos los elementos de a, devuelve el valor más alto del string

array([-1])

In [50]:
np.char.array("Como funciona esto",3)
#Repite los caracteres, dependiendo del número que se le dé

chararray(['Com', 'Com', 'Com', 'Com', 'Com', 'Com'], dtype='<U3')

## Binary Operations

In [51]:
a = np.array([[[1,0,1],[0,1,0]],[[1,1,0],[0,0,1]]])
b = np.packbits(a, axis=-1)
b
#Empaca el elemento de un arreglo valuado como binario, en arreglos 

array([[[160],
        [ 64]],

       [[192],
        [ 32]]], dtype=uint8)

 2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)

In [52]:
vec1=np.random.random((4,4))
vec2=np.arange(1,9,0.2)

np.savez("arreglos.bin",objetoA=vec1, objetoB=vec2)

In [53]:
d=np.load("arreglos.bin.npz")

In [54]:
d["objetoA"]

array([[0.97232716, 0.40982154, 0.58579131, 0.98867009],
       [0.64892111, 0.58030919, 0.62443861, 0.43299241],
       [0.95727721, 0.88229143, 0.89077498, 0.78820011],
       [0.64076401, 0.96911743, 0.92041958, 0.22367302]])

In [55]:
d["objetoB"]

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8])

In [56]:
h=np.random.random((5,5))
np.save("array",h)

In [57]:
H=np.load("array.npy")
h

array([[0.35134737, 0.5351947 , 0.25633037, 0.43356636, 0.11846148],
       [0.09625478, 0.31977791, 0.3754598 , 0.0637303 , 0.22050856],
       [0.93859436, 0.77121596, 0.74978018, 0.701884  , 0.81544705],
       [0.42389754, 0.26561268, 0.87399422, 0.22337992, 0.21849014],
       [0.27588379, 0.61739126, 0.76997477, 0.95267717, 0.86625256]])

3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    

In [60]:
vec1=np.random.random((10,10))
vec2=np.arange(2,7,0.1)
np.savetxt("proeba", vec1, delimiter=",")

In [61]:
np.loadtxt("proeba",delimiter=",")

array([[0.88650983, 0.01501301, 0.02532087, 0.71764424, 0.85157867,
        0.81026359, 0.6750676 , 0.29371574, 0.446964  , 0.26907898],
       [0.34829602, 0.56984119, 0.60222414, 0.0391587 , 0.49911371,
        0.72110807, 0.85207413, 0.73134234, 0.68866604, 0.2914111 ],
       [0.03409827, 0.52167333, 0.43421267, 0.2549773 , 0.50634594,
        0.36865907, 0.92951145, 0.79901683, 0.54607473, 0.55924299],
       [0.30362277, 0.13506055, 0.62974813, 0.60331662, 0.32770369,
        0.56811887, 0.11951382, 0.35515674, 0.39527139, 0.16726866],
       [0.93272094, 0.06950162, 0.27519107, 0.26262546, 0.82025422,
        0.99649456, 0.3741266 , 0.88677885, 0.60650377, 0.89846432],
       [0.80703165, 0.4405298 , 0.6113881 , 0.26238657, 0.33758367,
        0.2599917 , 0.60324681, 0.55559163, 0.63073246, 0.97060904],
       [0.34111568, 0.16869096, 0.21071013, 0.47411961, 0.63846373,
        0.04145388, 0.25161539, 0.48067036, 0.82459676, 0.40421162],
       [0.68613931, 0.68080408, 0.3669734

4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [62]:
import csv


def estimacionMCO():
    f=str(input("Ingrese el nombre del archivo: " ))+".csv"
    mat=np.genfromtxt(f,delimiter=",")
    X=mat[1: , :6]
    Y=mat[1:, 6: ]
    
    
    B1=(X.T)@X
    B11=np.linalg.inv(B1)
    B2=(X.T)@Y
    BETAS=B11@B2
    
    return(BETAS)
        

In [63]:
estimacionMCO()

Ingrese el nombre del archivo: Libro1


array([[0.04035055],
       [0.01655168],
       [0.045871  ],
       [0.02389826],
       [0.10755604],
       [0.21086565]])